import org.apache.spark.sql.functions._

// Generated by Vidhya's AI Agent for Azure Synapse
val df = spark.read.table("SALES_DATA")
val optimizedDf = df.repartition(col("TRANSACTION_DATE"))
optimizedDf.write.mode("overwrite").saveAsTable("SALES_DATA_OPTIMIZED")