package com.vidhya.ai;

import org.springframework.stereotype.Service;
import java.sql.*;
import java.nio.file.*;
import java.io.IOException;

@Service
public class SynapseAgent {

    // This is the method the Controller will call
    public String runOptimization() {
        StringBuilder result = new StringBuilder();
        result.append("--- Starting Enterprise AI Agent ---\n");
        
        try (Connection conn = DriverManager.getConnection("jdbc:h2:./synapse_db;IFEXISTS=FALSE", "sa", "")) {
            // 1. Scan the database
            DatabaseMetaData metaData = conn.getMetaData();
            
            String targetColumn = "TRANSACTION_DATE"; // The agent "chooses" this to optimize
            
            // 2. The Agentic Output: Generate a Physical Scala File
            String scalaCode = 
                "import org.apache.spark.sql.functions._\n\n" +
                "// Generated by Vidhya's AI Agent for Azure Synapse\n" +
                "val df = spark.read.table(\"SALES_DATA\")\n" +
                "val optimizedDf = df.repartition(col(\"" + targetColumn + "\"))\n" +
                "optimizedDf.write.mode(\"overwrite\").saveAsTable(\"SALES_DATA_OPTIMIZED\")";

            Files.write(Paths.get("OptimizeSynapse.scala"), scalaCode.getBytes());
            
            result.append("✅ Database Scanned Successfully.\n");
            result.append("🚀 AGENT ACTION: Created 'OptimizeSynapse.scala' for 5TB Data Partitioning.");
            
            return result.toString();

        } catch (SQLException | IOException e) {
            return "Error: " + e.getMessage();
        }
    }
}